engines:
  eslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
        - javascript
  fixme:
    enabled: true
    exclude_paths:
      - .codeclimate.yml
    config:
      strings:
        - TODO
        - console
ratings:
  paths:
  - src/**
exclude_paths:
- test/**/*
- docs/**/*
- demo/**/*
