language: node_js
node_js:
  - 10
after_success:
  - npm run cover
before_deploy:
  - npm install
  - npm run build
  - npm run svg
  - npm run card
  - cp site/index.html site/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site
  on:
    branch: master
