language: node_js
node_js:
  - 10
after_success:
  - npm run cover
before_deploy:
  - cd site
  - npm install
  - npm run build
  - npm run svg
  - cp card.png dist
  - cp dist/index.html dist/404.html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: site/dist
  on:
    branch: master
